### ISSUE TITLE
не дублируй версии прошивки отдельными папками

### ISSUE THREAD

**Issue by ivang7** [AlexGyver/GyverLight#5]
привет.

исправления, обновления и альтернативные версии не нужно заливать в виде отдельных папок, это противоречит сути git.
исправления и обновления можно выполнять в тех же файлах, история будет видна в коммитах.
альтернативные версии лучше оформлять отдельными ветками.

это позволит удобно смотреть историю кода и изменения.

на все выше перечисленное можно так же давать прямые ссылки для скачивания тем, кто не знаком с версионированием и гит в частности.

**Comment by AlexGyver** [comment]
99.99% повторяющих проект не знакомы с гитом вообще. Гит для проекта используется как обычное облачное хранилище файлов, где есть старые и новые версии в виде физических файлов.
Господи о чём мы говорим, большинство людей скачать то отсюда не могут, поэтому кнопку "скачать архив" пришлось сделать отдельной кнопкой.

**Comment by ivang7** [comment]
раз кнопки отдельные делать, то тем более, можно сразу ссылку на скачивание конкретного коммита (или вариант с ветками), зато тем, кто знакомы с гитом будет удобнее, просто пожелания для удобного оформления

**Comment by AlexGyver** [comment]
> раз кнопки отдельные делать, то тем более, можно сразу ссылку на скачивание конкретного коммита (или вариант с ветками), зато тем, кто знакомы с гитом будет удобнее, просто пожелания для удобного оформления

ну вот я с гитом как раз не знаком =)
